### ISSUE TITLE
Compatibility with data got from using different versions of sequencing chemistry?

### ISSUE THREAD

**Issue by ShangjinTan** [WGLab/DeepMod#11]
The nanopore technology is evolving fast. I wondered if the trained model is compatible with data produced by using different versions of sequencing chemistry.

**Comment by DAVID2022** [comment]
Yes, I also wonder will the trained model of deepmod be compatible with different sequencing kits and flow cells of ONT?

**Comment by liuqianhn** [comment]
Hi @ShangjinTan , @DAVID2022 , it is a good question. But I believe the effect of different sequencing chemistry is not very significant. There is one evidence in our paper: majority of e. coli data were sequenced by R9, while NA12878 were sequenced almost by R9.4. The cross-species testing show DeepMod achieved an accurate prediction.  

But the version of basecallers may affect the performance, since I found that signals segmentations by different versions of basecallers contains some significant deviation. Thus, it would be cautious to work on datasets with different versions of basecallers. 

Please feel free to share your idea and results about this question. Thank you.

**Comment by DAVID2022** [comment]
Thank you very much for your kind help!
