### ISSUE TITLE
Question about the format of input data

### ISSUE THREAD

**Issue by DAVID2022** [WGLab/DeepMod#16]
As albacore will output two subfolder in the workspace, one named"fail",  another one named "pass", should I put both fail and pass fast5 file into DeepMod to do the methylation analysis? If I should , should I set the "--recursive" of  "DeepMod.py detect " to 2 ? as there are two-layer folder.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , if you have high coverage data, it would be better to only use those reads from 'pass' folder. I have no evidence to show how 'fail' reads would make the prediction worse or better. But if you want to use both reads from 'fail' and 'pass', you can just set '--recursive 1' not '2' since the program uses the bool value from this parameter.

**Comment by DAVID2022** [comment]
thank you very much!
